# config/build.yaml
---
include:
  - board: supermini_nrf52840
    shield: DEIN_TASTATUR_SHIELD_LEFT
  - board: supermini_nrf52840
    shield: DEIN_TASTATUR_SHIELD_RIGHT
  - board: supermini_nrf52840
    shield: settings_reset
